=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22/Ejercicio-XSD-5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="grupo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1" />
              <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="2" />
              <xs:element name="fechaNacimiento" type="xs:date" maxOccurs="1" />
              <xs:element name="numeroDocumento" type="xs:int" />
              <xs:element name="local" type="xs:boolean" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
<!-- 
  He tenido que añadir la etiqueta "sequence" y y la propiedad "maxOccurs=Unbounded" para que el
  elemento "persona" funcione como aparece en el enunciado 
-->
<!--
  Como bien aparece en el enunciado "minOccurs=1" & "maxOccurs=1" es totalmente innecesario
  ponerlo porque los elementos están dentro de una secuencia, asi que ese es su valor por defecto
-->
<!-- 
  He cambiado los nombre de los elementos correspondientes a formato "camelCase" porque me resulta más fácil de leer
-->
<!-- 
  El elemento "numeroDocumento" podría estar mejor definido para limitar los dígitos y la polaridad del número
-->

=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22_XML-XSD/Ejercicio-XSD-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Ejercicio-XSD-5.css" type="text/css"?>
<grupo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio-XSD-5.xsd">
  <persona>
    <nombre >Luis</nombre>
    <apellido>PÃ©rez</apellido>
    <apellido>Sierra</apellido>
    <fechaNacimiento>1999-10-05</fechaNacimiento>
    <numeroDocumento>33444555</numeroDocumento>
    <local>true</local>
  </persona>
  <persona>
    <nombre>Marta</nombre>
    <apellido>Ortega</apellido>
    <fechaNacimiento>1998-05-23</fechaNacimiento>
    <numeroDocumento>44556677</numeroDocumento>
    <local>false</local>
  </persona>
</grupo>
