=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22/Ejercicio-XSD-1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fichasEstudiantes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fichaEstudiante" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:normalizedString" />
              <xs:element name="apellidos" type="xs:normalizedString" />
              <xs:element name="direccion" type="xs:normalizedString" />
              <xs:element name="codigoPostal" type="tipoCP" />
              <xs:element name="edad" type="tipoEdad" />
              <xs:element name="cicloFormativo" type="tipoCiclo" />
              <xs:element name="claveCiclo" type="tipoClave" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoCP">
    <xs:restriction base="xs:positiveInteger">
      <xs:totalDigits value="5"></xs:totalDigits>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoEdad">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="18" />
      <xs:maxInclusive value="65" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoCiclo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DAM" />
      <xs:enumeration value="DAW" />
      <xs:enumeration value="SMR" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoClave">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z0-9]{6}" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22/Ejercicio-XSD-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichasEstudiantes xsi:noNamespaceSchemaLocation="Ejercicio-XSD-1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <fichaEstudiante>
    <nombre>Marcos</nombre>
    <apellidos>Fernández Ramos</apellidos>
    <direccion>Calle Honduras 30</direccion>
    <codigoPostal>28822</codigoPostal>
    <edad>26</edad>
    <cicloFormativo>DAM</cicloFormativo>
    <claveCiclo>DAM666</claveCiclo>
  </fichaEstudiante>
  <fichaEstudiante>
    <nombre>Fernando</nombre>
    <apellidos>Rodríguez López</apellidos>
    <direccion>Calle Uruguay 128</direccion>
    <codigoPostal>28820</codigoPostal>
    <edad>21</edad>
    <cicloFormativo>DAW</cicloFormativo>
    <claveCiclo>daw616</claveCiclo>
  </fichaEstudiante>
</fichasEstudiantes>
