=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22/Ejercicio-XSD-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:normalizedString" />
              <xs:element name="direccion" type="xs:normalizedString" />
              <xs:element name="ciudad" type="xs:normalizedString" />
              <xs:element name="CP" type="tipoCP" minOccurs="0" />
              <xs:element name="telefono" type="tipoTlfn" maxOccurs="3" />
              <xs:element name="titulacion" type="tipoTitulo" />
            </xs:sequence>
            <xs:attribute name="cod" type="xs:positiveInteger" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoCP">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:totalDigits value="5" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoTlfn">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:totalDigits value="9" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoTitulo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TÃ©cnico" />
      <xs:enumeration value="Superior" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22/Ejercicio-XSD-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Ejercicio-XSD-2.xsd">
  <empleado cod="1">
    <nombre>Ana Pérez Solís</nombre>
    <direccion>c/ Mayor, 27</direccion>
    <ciudad>Madrid</ciudad>
    <CP>28026</CP>
    <telefono>912345678</telefono>
    <telefono>655914567</telefono>
    <titulacion>Superior</titulacion>
  </empleado>
  <empleado cod="2">
    <nombre>Pedro Muñoz Solís</nombre>
    <direccion>c/ Alcantara, 34</direccion>
    <ciudad>Madrid</ciudad>
    <telefono>656123336</telefono>
    <titulacion>Técnico</titulacion>
  </empleado>
</empleados>
