=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22_XML-XSD/Ejercicio-XSD-3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listaTitulos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cuaderno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:normalizedString" />
              <xs:choice>
                <xs:element name="autor" type="xs:normalizedString" maxOccurs="unbounded" />
                <xs:element name="autor1" type="xs:normalizedString" />
              </xs:choice>
              <xs:element name="editorial" type="xs:normalizedString" />
              <xs:element name="descripcion" type="xs:normalizedString" minOccurs="0" />
              <xs:element name="precio" type="xs:positiveInteger" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
<!-- 
  He cambiado los nombre de los elementos correspondientes a formato "camelCase" porque me resulta más fácil de leer
 -->

=== aniballpxess/CursoFP/LLMM/Angeles/PRACTICA/Entorno_VS-Code/Tareas/24-04-22_XML-XSD/Ejercicio-XSD-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaTitulos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Ejercicio-XSD-3.xsd">
  <cuaderno>
    <titulo>Photoshop</titulo>
    <autor>Michael Karbo</autor>
    <autor>Peter G. Christiansen</autor>
    <editorial>PC Cuadernos</editorial>
    <precio>4</precio>
  </cuaderno>
  <cuaderno>
    <titulo>Cree su página Web (I)</titulo>
    <autor1>Johann-Christian Hanke</autor1>
    <editorial>PC Cuadernos</editorial>
    <descripcion>Introducción a HTML</descripcion>
    <precio>4</precio>
  </cuaderno>
  <cuaderno>
    <titulo>El registro de Windows</titulo>
    <autor>David Bosman</autor>
    <editorial>PC Cuadernos</editorial>
    <descripcion>Trucos para editar el registro</descripcion>
    <precio>4</precio>
  </cuaderno>
</listaTitulos>
